### ISSUE TITLE
VideoFrame.Save() not setting color_range for output frame

### ISSUE THREAD

**Issue by RyanYANG52** [dubiousconst282/FFmpegWrapper#6]
Hi @dubiousconst282 , I am using `VideoFrame.Save()` to take a jpg snapshot of a video, I noticed that the jpg'color is whitening than png output

https://github.com/dubiousconst282/FFmpegWrapper/blob/4f46e5e4e67799d4aefbb19c7e8646a9e074f433/FFmpegWrapper/VideoFrame.cs#L224-L236

this code here only set color_range for encoder, but tempFrame colorSpace is copy from src, `tempFrame.Colorspace = Colorspace; `, so `sws.SetColorspace` will have no effect, `AVCOL_RANGE_MPEG` in and `AVCOL_RANGE_MPEG` out. encoder will treat MPEG as JPEG, result into wrong color range

I add one line after, and it output the same color range like png.
```csharp
tempFrame.Colorspace = Colorspace; 
if (jpeg) tempFrame.Handle->color_range = AVColorRange.AVCOL_RANGE_JPEG;
```
---

In my testing, I also find out if src and dst have the same pixel format, `sws_setColorspaceDetails` will have no effects, I change to `var pixFmt = jpeg ? AVPixelFormat.AV_PIX_FMT_YUV420P : AVPixelFormat.AV_PIX_FMT_RGBA;` then `SetColorspace`, color still off. Maybe a bug in sws_scale, similar to this https://trac.ffmpeg.org/ticket/4805

I imagine if src format is also AV_PIX_FMT_YUV444P, it may fail to change color range also. 

I test using `YUVJ444P` instead, it works without setting colorspace, but it's [deprecated pixel format used](https://stackoverflow.com/questions/23067722/swscaler-warning-deprecated-pixel-format-used)

**Comment by dubiousconst282** [comment]
Thanks for spotting this.

After applying the suggested fix for color_range the first issue indeed seems to go away for most part, and I found that further creating SwScaler with the `InterpolationMode.HighQuality` flag makes for almost identical outputs compared to PNG (albeit probably with a slight impact in performance).

None of this works for HDR sources, I think because JPEG does not support color profiles and because swscale does not support this sort of remapping, but that's a niche case anyway and it's possible to filter beforehand using either zscale or libplacebo. (A tiny wrapper for these with a similar interface to swscale have been on my bucket list for a while, so I might revisit it at some time.)

---

Also, as you found, it seems that when the pixel formats and dimensions are the same, swscale is hardcoded to simply copy the data without applying any conversions: 
https://github.com/FFmpeg/FFmpeg/blob/08781ebe1aabe99b94e2ee949ca0c95c1443c756/libswscale/swscale_unscaled.c#L2212-L2227

They do have an earlier check but it only kicks in if the colorspace matrices are different, which invokes a fallback to intermediate RGB conversions:
https://github.com/FFmpeg/FFmpeg/blob/08781ebe1aabe99b94e2ee949ca0c95c1443c756/libswscale/utils.c#L1097-L1101

I'm not sure if it's worth reporting/submitting a patch upstream, but I suppose that since YUV444 sources seem to be relatively rare, it would be acceptable to manually replicate this intermediate RGB conversion here. (Will implement tomorrow.)
